#!/bin/bash

### BEGIN INIT INFO
# Provides:          neutrino
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start neutrino proxy-server
### END INIT INFO

DESC="Neutrino proxy-server service"
NAME=neutrino
DAEMON=/bin/bash
DAEMON_ARGS="/usr/bin/neutrino-start.sh"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
  start)
    echo "Starting $DESC: $NAME"
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
    echo "$NAME started."
    ;;
  stop)
    echo "Stopping $DESC: $NAME"
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
    echo "$NAME stopped."
    ;;
  restart|force-reload)
    echo "Restarting $DESC: $NAME"
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
    echo "$NAME restarted."
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0